--- #YAML:1.0
name:               Business-OnlinePayment-Cardcom
version:            0.02
abstract:           ~
author:
    - Erik Levinson <levinse@freeside.biz>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::OnlinePayment:  0
    Net::HTTPS::Any:      0
    Tie::IxHash:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
